spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:final-mission-jjimggong

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  sendgrid:
    from: zkffl0@naver.com
    api-key: SG.로 시작하는 API Key


security:
  jwt:
    token:
      secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
      expire-length: 3600000

