name: prod-cd.yml
on:
  push:
    branches: [ "main" ]
    paths:
      - "**"

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
        working-directory: ./

      - name: Build project
        run: ./gradlew clean build -x test
        working-directory: ./

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Multi-Arch Image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mission:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mission:${{ github.sha }}

  deploy:
    runs-on: [ self-hosted, linux ]
    needs: build-and-push
    steps:
      - name: Stop and remove existing container
        run: |
          if [ "$(docker ps -a -q -f name=backend-app)" ]; then
            docker stop backend-app
            docker rm -f backend-app
          fi

      - name: Pull latest image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mission:latest

      - name: Create .env file
        run: |
          cat <<EOF > ~/mission/.env
          PROD_DATASOURCE_URL=${{ secrets.PROD_DATASOURCE_URL }}
          PROD_DATASOURCE_USERNAME=${{ secrets.PROD_DATASOURCE_USERNAME }}
          PROD_DATASOURCE_PASSWORD=${{ secrets.DATASOURCE_PASSWORD }}
          PROD_DEV_DB_PASSWORD=${{ secrets.PROD_DEV_DB_PASSWORD }}
          SPRING_PROFILES_ACTIVE=prod
          EOF

      - name: Stop existing services
        run: sudo docker compose stop backend-app
        working-directory: /home/ubuntu/mission

      - name: Start new services
        run: sudo docker compose up -d backend-app
        working-directory: /home/ubuntu/mission
